export const GET_PROJECTS = 'PROJECT/GET_ALL';
export const GET_PROJECTS_SUCCESS = 'PROJECT/GET_ALL_SUCCESS';

export const GET_INVITATIONS = 'USER/GET_INVITATIONS';
export const GET_INVITATIONS_SUCCESS = 'USER/GET_INVITATIONS_SUCCESS';

export const CREATE_PROJECT = 'USER/CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'USER/CREATE_PROJECT_SUCCESS';

export const ARCHIVE_PROJECT = 'USER/ARCHIVE_PROJECT';
export const UNARCHIVE_PROJECT = 'USER/UNARCHIVE_PROJECT';
export const DELETE_PROJECT = 'USER/DELETE_PROJECT';

export const ACCEPT_INVITATION = 'user/ACCEPT_INVITATION';
export const DECLINE_INVITATION = 'user/DECLINE_INVITATION';


export const UPDATE_INVITATION = 'USER/UPDATE_INVITATION';

export const SET_NOTIFICATIONS_SEEN = 'USER/GET_NOTIFICATIONS';

export const CREATE_NOTIFICATION = 'USER/CREATE_NOTIFICATION';
